### PR TITLE
Adding transparency to the screenshot

### PR DESCRIPTION
**Pull request by cyperdark**

### CODE REVIEW

**Comment by juliangruber** [comment]
Thank you for this patch!

I've tried this and didn't find a site without a white background where I could test this. What do you want this change for?

Also I noticed that with this change the `height` and `width` properties are ignored and the output will always be as large as the `body` element itself.

**Comment by cyperdark** [comment]
i use that for create png of the graph (d3js) 
1695382-72_800x250-red
2129143-72_800x250-red
1031991-0_800x200-red

**Comment by juliangruber** [comment]
have you looked at http://bl.ocks.org/Rokotyan/0556f8facbaf344507cdc45dc3622177?

**Comment by cyperdark** [comment]
yeah but i use script for auto generate this charts so this method best for me

**Pull request closed without merging**
